"""initial schema (ops + app)

Creates the two schemas (``ops`` and ``app``), every enum type, every table,
and every hot-path index. This is the first migration — hand-authored rather
than autogenerated so the ``CREATE SCHEMA`` statements run before any table
creation.

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-04-15

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Schemas must exist before any table / type creation.
    op.execute("CREATE SCHEMA IF NOT EXISTS ops")
    op.execute("CREATE SCHEMA IF NOT EXISTS app")

    # ── Enum types ───────────────────────────────────────────────────────────
    lead_status = postgresql.ENUM(
        "new", "scanned", "extracted", "built", "review_pending",
        "approved", "emailed", "followed_up", "opened", "clicked", "purchased",
        "rejected", "bounced", "unsubscribed", "suppressed",
        "bad_email", "unreachable", "skipped_language",
        name="lead_status", schema="ops",
    )
    lead_status.create(op.get_bind(), checkfirst=False)

    email_status = postgresql.ENUM(
        "queued", "sent", "delivered", "opened", "clicked", "replied",
        "bounced", "complained", "suppressed", "failed",
        name="email_status", schema="ops",
    )
    email_status.create(op.get_bind(), checkfirst=False)

    suppression_reason = postgresql.ENUM(
        "unsubscribe", "bounce", "complaint", "manual",
        "competitor", "existing_customer",
        name="suppression_reason", schema="ops",
    )
    suppression_reason.create(op.get_bind(), checkfirst=False)

    site_status = postgresql.ENUM(
        "draft", "review_pending", "approved", "live", "expired", "purchased",
        name="site_status", schema="app",
    )
    site_status.create(op.get_bind(), checkfirst=False)

    payment_status = postgresql.ENUM(
        "pending", "succeeded", "refunded", "disputed", "failed",
        name="payment_status", schema="app",
    )
    payment_status.create(op.get_bind(), checkfirst=False)

    # ── ops.leads ────────────────────────────────────────────────────────────
    op.create_table(
        "leads",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("business_name", sa.String(255), nullable=False),
        sa.Column("vertical", sa.String(64), nullable=False),
        sa.Column("website_url", sa.String(1024), nullable=False),
        sa.Column("canonical_domain", sa.String(255), nullable=False, unique=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("phone", sa.String(64), nullable=True),
        sa.Column("city", sa.String(128), nullable=True),
        sa.Column("country", sa.String(8), nullable=False),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="lead_status", schema="ops", create_type=False),
            nullable=False,
            server_default="new",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ops",
    )
    op.create_index("idx_leads_vertical_country", "leads", ["vertical", "country"], schema="ops")
    op.create_index("ix_ops_leads_vertical", "leads", ["vertical"], schema="ops")
    op.create_index("ix_ops_leads_country", "leads", ["country"], schema="ops")
    op.create_index("ix_ops_leads_status", "leads", ["status"], schema="ops")

    # ── ops.scans ────────────────────────────────────────────────────────────
    op.create_table(
        "scans",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("score", sa.Integer, nullable=False),
        sa.Column("pass_fail", sa.Boolean, nullable=False),
        sa.Column("issues_json", postgresql.JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("pagespeed_mobile", sa.Integer, nullable=True),
        sa.Column("pagespeed_desktop", sa.Integer, nullable=True),
        sa.Column("has_ssl", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("has_mobile", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("has_analytics", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("screenshot_r2_key", sa.String(512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["ops.leads.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("lead_id", name="uq_scans_lead_id"),
        schema="ops",
    )

    # ── ops.extractions ──────────────────────────────────────────────────────
    op.create_table(
        "extractions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("strategy_name", sa.String(64), nullable=False),
        sa.Column("content_json", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("images_json", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("brand_colors", postgresql.JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("vision_model_version", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["ops.leads.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("lead_id", name="uq_extractions_lead_id"),
        schema="ops",
    )

    # ── ops.emails ───────────────────────────────────────────────────────────
    op.create_table(
        "emails",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sequence_step", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("subject", sa.String(512), nullable=False),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(name="email_status", schema="ops", create_type=False),
            nullable=False,
            server_default="queued",
        ),
        sa.Column("backend_name", sa.String(64), nullable=True),
        sa.Column("smtp_inbox_used", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["ops.leads.id"], ondelete="CASCADE"),
        schema="ops",
    )
    op.create_index("idx_emails_lead_id_step", "emails", ["lead_id", "sequence_step"], schema="ops")
    op.create_index("idx_emails_status_sent_at", "emails", ["status", "sent_at"], schema="ops")

    # ── ops.suppression_list ─────────────────────────────────────────────────
    op.create_table(
        "suppression_list",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("domain", sa.String(255), nullable=True),
        sa.Column(
            "reason",
            postgresql.ENUM(name="suppression_reason", schema="ops", create_type=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ops",
    )
    op.create_index(
        "idx_suppression_email",
        "suppression_list",
        ["email"],
        schema="ops",
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_index("idx_suppression_domain", "suppression_list", ["domain"], schema="ops")

    # ── ops.events ───────────────────────────────────────────────────────────
    op.create_table(
        "events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(128), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["ops.leads.id"], ondelete="CASCADE"),
        schema="ops",
    )
    op.create_index("idx_events_lead_id_created", "events", ["lead_id", "created_at"], schema="ops")
    op.create_index("idx_events_type", "events", ["event_type"], schema="ops")

    # ── app.sites ────────────────────────────────────────────────────────────
    op.create_table(
        "sites",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(32), nullable=False, unique=True),
        sa.Column("preview_url", sa.String(1024), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="site_status", schema="app", create_type=False),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["ops.leads.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("lead_id", name="uq_sites_lead_id"),
        schema="app",
    )
    op.create_index("ix_app_sites_status", "sites", ["status"], schema="app")
    op.create_index(
        "idx_sites_expires_at",
        "sites",
        ["expires_at"],
        schema="app",
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )

    # ── app.payments ─────────────────────────────────────────────────────────
    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(255), nullable=False, unique=True),
        sa.Column("amount_cents", sa.Integer, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="payment_status", schema="app", create_type=False),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("raw_webhook", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["ops.leads.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("stripe_payment_intent_id", name="uq_payments_pi"),
        schema="app",
    )
    op.create_index("ix_app_payments_status", "payments", ["status"], schema="app")


def downgrade() -> None:
    # Tables first (indexes drop with them), then enum types, then schemas.
    op.drop_table("payments", schema="app")
    op.drop_table("sites", schema="app")
    op.drop_table("events", schema="ops")
    op.drop_table("suppression_list", schema="ops")
    op.drop_table("emails", schema="ops")
    op.drop_table("extractions", schema="ops")
    op.drop_table("scans", schema="ops")
    op.drop_table("leads", schema="ops")

    for enum_name, schema in [
        ("payment_status", "app"),
        ("site_status", "app"),
        ("suppression_reason", "ops"),
        ("email_status", "ops"),
        ("lead_status", "ops"),
    ]:
        postgresql.ENUM(name=enum_name, schema=schema).drop(op.get_bind(), checkfirst=False)

    op.execute("DROP SCHEMA IF EXISTS app")
    op.execute("DROP SCHEMA IF EXISTS ops")
